function plot_fractions(saveFlag, debugFlag)
tic;

Z_0_0200 = load('../data/fraction_Z_0.02.mat');
Z_0_0142 = load('../data/fraction_Z_0.0142.mat');
Z_0_0100 = load('../data/fraction_Z_0.01.mat');
Z_0_0047 = load('../data/fraction_Z_0.0047.mat');
Z_0_0021 = load('../data/fraction_Z_0.0021.mat');
Z_0_0010 = load('../data/fraction_Z_0.001.mat');
Z_0_0002 = load('../data/fraction_Z_0.0002.mat');
Z_0_0001 = load('../data/fraction_Z_0.0001.mat');

metallicity             = [ 0.0200 ...
                            0.0142 ...
                            0.0100 ...
                            0.0047 ...
                            0.0021 ...
                            0.0010 ...
                            0.0002 ...
                            0.0001];
% Single
fraction_abs_BH_sin_mass_2_5   = [ Z_0_0200.fraction_abs_BH_sin_mass_2_5 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_2_5 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_2_5 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_2_5 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_2_5 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_2_5 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_2_5 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_2_5];

fraction_abs_BH_sin_mass_4   = [ Z_0_0200.fraction_abs_BH_sin_mass_4 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_4 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_4 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_4 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_4 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_4 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_4 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_4];

fraction_abs_BH_sin_mass_5   = [ Z_0_0200.fraction_abs_BH_sin_mass_5 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_5 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_5 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_5 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_5 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_5 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_5 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_5];

fraction_abs_BH_sin_mass_6   = [ Z_0_0200.fraction_abs_BH_sin_mass_6 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_6 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_6 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_6 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_6 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_6 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_6 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_6];

fraction_abs_BH_sin_mass_8   = [ Z_0_0200.fraction_abs_BH_sin_mass_8 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_8 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_8 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_8 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_8 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_8 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_8 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_8];

fraction_abs_BH_sin_mass_10   = [ Z_0_0200.fraction_abs_BH_sin_mass_10 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_10 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_10 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_10 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_10 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_10 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_10 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_10];

fraction_abs_BH_sin_mass_12   = [ Z_0_0200.fraction_abs_BH_sin_mass_12 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_12 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_12 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_12 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_12 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_12 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_12 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_12];

fraction_abs_BH_sin_mass_14   = [ Z_0_0200.fraction_abs_BH_sin_mass_14 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_14 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_14 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_14 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_14 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_14 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_14 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_14];

fraction_abs_BH_sin_mass_15   = [ Z_0_0200.fraction_abs_BH_sin_mass_15 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_15 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_15 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_15 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_15 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_15 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_15 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_15];

fraction_abs_BH_sin_mass_16   = [ Z_0_0200.fraction_abs_BH_sin_mass_16 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_16 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_16 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_16 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_16 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_16 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_16 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_16];

fraction_abs_BH_sin_mass_18   = [ Z_0_0200.fraction_abs_BH_sin_mass_18 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_18 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_18 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_18 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_18 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_18 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_18 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_18];

fraction_abs_BH_sin_mass_20   = [ Z_0_0200.fraction_abs_BH_sin_mass_20 ...
                                 Z_0_0142.fraction_abs_BH_sin_mass_20 ...
                                 Z_0_0100.fraction_abs_BH_sin_mass_20 ...
                                 Z_0_0047.fraction_abs_BH_sin_mass_20 ...
                                 Z_0_0021.fraction_abs_BH_sin_mass_20 ...
                                 Z_0_0010.fraction_abs_BH_sin_mass_20 ...
                                 Z_0_0002.fraction_abs_BH_sin_mass_20 ...
                                 Z_0_0001.fraction_abs_BH_sin_mass_20];

if debugFlag
    single_fraction_mass_5
    single_fraction_mass_10
    single_fraction_mass_15
    single_fraction_mass_20
    single_fraction_mass_100
    binary_fraction_mass_5
    binary_fraction_mass_10
    binary_fraction_mass_15
    binary_fraction_mass_20
    binary_fraction_mass_100
    fraction_abs_BH_sin_mass_2_5
    fraction_abs_BH_sin_mass_5
    fraction_abs_BH_sin_mass_10
    fraction_abs_BH_sin_mass_15
    fraction_abs_BH_sin_mass_20
end

% Plot
figure()

color1 = [         0         0    0.0417];
color2 = [             0.0972    0.0972    0.1806];
color3 = [             0.1944    0.1944    0.3194];
color4 = [             0.2917    0.3333    0.4167];
color5 = [             0.3889    0.4722    0.5139];
color6 = [             0.4861    0.6111    0.6111];
color7 = [             0.6146    0.7083    0.7083];
color8 = [             0.7431    0.8056    0.8056];
color9 = [             0.8715    0.9028    0.9028];

fs=18;
lw=2.0;
string1='Z';  

% Single
hold on
xticks([0.0001 0.005 0.01 0.015 0.02])
ylim([0.1 1])
xlabel(string1,'FontSize',fs,'FontName','Times New Roman')
ax=gca;
ax.FontSize=fs;
ax.FontName = 'Times New Roman';
box on
ylabel('N_{sin} / N_{tot}','FontSize',fs,'FontName','Times New Roman')

plot(metallicity,fraction_abs_BH_sin_mass_20,'LineWidth',lw,'Color',color1)
plot(metallicity,fraction_abs_BH_sin_mass_18,'LineWidth',lw,'Color',color2)
plot(metallicity,fraction_abs_BH_sin_mass_16,'LineWidth',lw,'Color',color3)
plot(metallicity,fraction_abs_BH_sin_mass_14,'LineWidth',lw,'Color',color4)
plot(metallicity,fraction_abs_BH_sin_mass_12,'LineWidth',lw,'Color',color5)
plot(metallicity,fraction_abs_BH_sin_mass_10,'LineWidth',lw,'Color',color6)
plot(metallicity,fraction_abs_BH_sin_mass_8,'LineWidth',lw,'Color',color7)
plot(metallicity,fraction_abs_BH_sin_mass_6,'LineWidth',lw,'Color',color8)
plot(metallicity,fraction_abs_BH_sin_mass_4,'LineWidth',lw,'Color',color9)
legend( '$M \geq 20\ \rm{M_{\odot}}$',...
        '$M \geq 18\ \rm{M_{\odot}}$',...
        '$M \geq 16\ \rm{M_{\odot}}$',...        
        '$M \geq 14\ \rm{M_{\odot}}$',...
        '$M \geq 12\ \rm{M_{\odot}}$',...
        '$M \geq 10\ \rm{M_{\odot}}$',...
        '$M \geq 8\ \rm{M_{\odot}}$',...        
        '$M \geq 6\ \rm{M_{\odot}}$',...
        '$M \geq 4\ \rm{M_{\odot}}$',...        
        'Location','Eastoutside',...
        'Interpreter','latex',...
        'box','off')

if saveFlag
    print(gcf,strcat('../plots/png/figure5_single.png'),'-dpng','-r300');
    saveas(gcf,strcat('../plots/pdf/figure5_single.pdf'))
end

toc;
end